require_relative './quotebook/api'
require_relative './quotebook/author'
require_relative './quotebook/cli'
require_relative './quotebook/quote'
require_relative './quotebook/version'

require 'pry'
require 'rake'
require 'httparty'
require 'net/http'
require 'tty-prompt'
require 'colorize'