require_relative './quotebook/api'
require_relative './quotebook/artwork'
require_relative './quotebook/author'
require_relative './quotebook/cli'
require_relative './quotebook/quote'
require_relative './quotebook/version'

require 'pry'
require 'rake'
require 'json'
require 'httparty'
require 'net/http'
require 'tty-table'
require 'tty-prompt'
require 'tty-box'
require 'tty-font'
require 'colorize'
require 'table_print'